- CHANGELOG.md
- example/pubspec.lock
- lib/horizontal_data_table.dart
- pubspec.lock
- pubspec.yaml
Resolves: https://github.com/MayLau-CbL/flutter_horizontal_data_table/issues/21
> Fix: null pt exceptiopn on dispose

- CHANGELOG.md
- README.md
- example/pubspec.lock
- lib/horizontal_data_table.dart
- pubspec.yaml
1. added new tableHeight allowing manually adjust table widget height
Resolves: #27
> Feature: new tableHeight param

- CHANGELOG.md
- example/pubspec.lock
- lib/delegate/base_layout_view_delegate.dart
- lib/delegate/list_view_layout_delegate.dart
- lib/horizontal_data_table.dart
- lib/scroll/sync_scroll_controller_manager.dart
- pubspec.lock
- pubspec.yaml
1. separated the private classes in dart file
2. updated base UI with CustomMultiChildLayout instead of Stack
3. removed unused methods
> Update: UI with CustomMultiChildLayout

- CHANGELOG.md
- README.md
- example/lib/main.dart
- example/pubspec.lock
- lib/horizontal_data_table.dart
- lib/scroll/custom_scroll_bar.dart
- lib/scroll/scroll_bar_style.dart
- pubspec.yaml
1. added vertical and horizontal custom scroll bar handling
2. updated example project deprecated widget
Resolves: https://github.com/MayLau-CbL/flutter_horizontal_data_table/issues/32
Resolves: https://github.com/MayLau-CbL/flutter_horizontal_data_table/issues/13
> Feature: custom scroll bar

- CHANGELOG.md
- README.md
- example/lib/main.dart
- example/pubspec.lock
- lib/scroll/custom_scroll_bar.dart
- lib/scroll/scroll_bar_style.dart
- pubspec.yaml
1. removed custom thumb color until RawScrollbar support in stable
> Update: disable scrollbar thumb color

- CHANGELOG.md
- README.md
- example/pubspec.lock
- lib/scroll/custom_scroll_bar.dart
- lib/scroll/scroll_bar_style.dart
- pubspec.yaml
1. enabled scroll bar color styling
Resolves: https://github.com/MayLau-CbL/flutter_horizontal_data_table/issues/35
> Feature: Scrollbar color style

- CHANGELOG.md
- README.md
- example/pubspec.lock
- pubspec.yaml
1. updated README.md for null-safty and scrollphysics info
2. updated version to 3.1.0
> Update: README.md null-safty and scrollphysics info

- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
> Update: version 3.2.0

- CHANGELOG.md
- README.md
- example/lib/main.dart
- example/pubspec.lock
- lib/horizontal_data_table.dart
- lib/scroll/custom_scroll_bar.dart
- lib/scroll/sync_horizontal_scroll_controller_manager.dart
- pubspec.yaml
1. added horizontal scroll physics
2. updated to make the vertical scrollbar always show on right even not the end of horizontal scroll
Related to: #45
> Update: Vertical Scrollbar Always Show On Right

- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
> Update: version config

- lib/scroll/sync_scroll_controller_manager.dart
This probably the simplest way to make it work. 
And this makes the refresh more smooth.
> Update sync_scroll_controller_manager.dart to make list refresh more smooth

- CHANGELOG.md
- README.md
- example/ios/Flutter/AppFrameworkInfo.plist
- example/lib/main.dart
- example/pubspec.lock
- lib/horizontal_data_table.dart
- lib/refresh/hdt_refresh_controller.dart
- pubspec.yaml
> Feature: add pull to load

- CHANGELOG.md
- example/pubspec.lock
- lib/scroll/scroll_bar_style.dart
- pubspec.yaml
> Update: dart format

- CHANGELOG.md
- example/pubspec.lock
- lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart
- lib/refresh/pull_to_refresh/src/smart_refresher.dart
- pubspec.lock
- pubspec.yaml
widgetbinding.instance handling after flutter 3.0.0 (fix #78 )
> Update: widgetbinding instance handling

- CHANGELOG.md
- example/pubspec.lock
- lib/refresh/pull_to_refresh/src/internals/indicator_wrap.dart
- lib/refresh/pull_to_refresh/src/smart_refresher.dart
- pubspec.yaml
1. fixed remaining widgetsbinding.instance?. issue for flutter 3.0.0
2. updated version
fix part of #84
> Fix: widgets binding.instance

- CHANGELOG.md
- README.md
- example/lib/main.dart
- example/pubspec.lock
- lib/delegate/base_layout_view_delegate.dart
- lib/horizontal_data_table.dart
- pubspec.lock
- pubspec.yaml
1. added rtl support
2. upgarded dependence to latest version
Resolve: #4
> Update: Right-to-left support

- CHANGELOG.md
- README.md
- example/pubspec.lock
- lib/delegate/base_layout_view_delegate.dart
- lib/horizontal_data_table.dart
- lib/scroll/sync_scroll_controller_manager.dart
- pubspec.yaml
1. refactored internal fields naming and simplified the constructor of rtl
2. updated README.md for package and flutter version compatability
> Update: refactor inner field naming

- CHANGELOG.md
- example/lib/data/user.dart
- example/lib/main.dart
- example/lib/simple_table_refresh_load_desktop.dart
- example/lib/simple_table_scroll_style.dart
- example/pubspec.lock
- pubspec.yaml
1. updated example data generation
2. updated desktop pull-to-refresh and custom scrollbar example
> Update: desktop example

- CHANGELOG.md
- example/lib/data/user.dart
- example/lib/main.dart
- example/lib/title_reorder_table.dart
- example/pubspec.lock
- pubspec.yaml
1. added reorder header and footer example
> Update: reorder header and footer example

- README.md
- example/pubspec.lock
- pubspec.yaml
1. updated README.md table of package version mapping
2. updated version number
> Update: specify package version to flutter version mapping

- CHANGELOG.md
- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
> Update: upgraded dependence

- CHANGELOG.md
- README.md
- example/lib/simple_table.dart
- example/pubspec.lock
- lib/horizontal_data_table.dart
- pubspec.yaml
This PR updated following:
1. run dart format
2. update version
3. update docs on README.md and comment
> Update: version formating docs

- CHANGELOG.md
- example/android/app/build.gradle
- example/android/app/src/debug/AndroidManifest.xml
- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/profile/AndroidManifest.xml
- example/android/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/lib/main.dart
- pubspec.yaml
1. upgraded android example project to latest gradle version
2. fixed web pull to refresh example not able to drag the refresh
3. updated version and changelog
> Feature: Update Android and Web Example Project

- CHANGELOG.md
- example/pubspec.lock
- lib/refresh/pull_to_refresh/src/internals/refresh_physics.dart
- pubspec.yaml
1. replaced tolerance with toleranceFor
2. updated version and changelog
> Fix: Replace Deprecated Tolerance
